### ISSUE TITLE
Global configs in konnect.yml

### ISSUE THREAD

**Issue by TunedMystic** [exitshell/konnect#28]
### Summary
Create global configs for Hosts that will be used if that specific field is not provided.

**BEFORE**: example `konnect.yml` file
```
hosts:
  app:
    user: ubuntu
    host: 192.169.99.95
    port: 22
    key: ~/keys/deploy.pem
  database:
    user: ubuntu
    host: 192.169.99.96
    port: 22
    key: ~/keys/deploy.pem
  redis:
    user: ubuntu
    host: 192.169.99.97
    port: 22
    key: ~/keys/deploy.pem
  webpack:
    user: ubuntu
    host: 192.169.99.98
    port: 22
    key: ~/keys/deploy.pem
```

In this example, the `user`, `port` and `key` are repetitive. It would be much better if we could define fields in some global config, and have those fields be applied to hosts that don't have them.

Something like:

**AFTER**: example `konnect.yml` file
```
global:
  user: ubuntu
  key: ~/keys/deploy.pem
  port: 22

hosts:
  app:
    host: 192.169.99.95
    key: ~/prod/keys/app.pem
  database:
    user: postgres
    host: 192.169.99.96
  redis:
    host: 192.169.99.97
  webpack:
    host: 192.169.99.98
```
